Pull across various changes originally made on the CRAN branch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2520,6 +2520,15 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 ac_config_headers="$ac_config_headers src/onig/config.h"
 
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+	echo "could not determine R_HOME"
+	exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
 STATISTICS=""
 
 # Check whether --with-statistics was given.
